name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://kenobijr:$HF_TOKEN@huggingface.co/spaces/kenobijr/eu-ai-act-bot main
